# build and deploy ICPC community websit
name: deploy ICPC community to monester asp.

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
    - name:  checkout code
      uses: actions/checkout@v4

    - name: setup .net
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: restore dependencies
      run: dotnet restore

    - name: build
      run: dotnet build --configuration Release

    - name: dotnet publish 
      run: dotnet publish --configuration Release --output /publish
    
   # - name: Deploy to Monester ASP.NET Server
    #  env:
     #   SFTP_SERVER: ${{ secrets.SFTP_SERVER }}
      #  SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
       # SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
       # SFTP_DESTINATION_PATH: ${{ secrets.SFTP_DESTINATION_PATH }}
      # run: |
        # Install lftp
       # sudo apt-get install -y lftp

        # Deploy using lftp
        #lftp -c "
        #open -u $SFTP_USERNAME,$SFTP_PASSWORD sftp://$SFTP_SERVER;
        #mirror -R ./publish $SFTP_DESTINATION_PATH;
        #"
