name: Build and Deploy ISc Solution

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release

      - name: Create artifact directory
        run: mkdir ./publish

      - name: Publish projects
        run: |
          dotnet publish ISc.Application/ISc.Application.csproj --configuration Release --output ./publish
          dotnet publish ISc.Domain/ISc.Domain.csproj --configuration Release --output ./publish
          dotnet publish ISc.Infrastructure/ISc.Infrastructure.csproj --configuration Release --output ./publish
          dotnet publish ISc.Presistance\ISc.Presistance.csproj --configuration Release --output ./publish
          ISc.Presentation\ISc.Presentation.csproj --configuration Release --output ./publish
          ISc.Shared\ISc.Shared.csproj --configuration Release --output ./publish    
          ISc.Api\ISc.Api.csproj --configuration Release --output ./publish 
          ISC.UnitTest\ISc.UnitTests.csproj --configuration Release --output ./publish


      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: site4208.siteasp.net
          username: site4208
          password: ${{ secrets.SFTP_PASSWORD }}
          local-dir: ./publish/
          server-dir: /wwwroot/
          delete: true
