# Build and deploy ICPC community website
name: Deploy ICPC community to Monester ASP.NET

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout develop branch code
      uses: actions/checkout@v4
      with:
        ref: develop  # Check out the develop branch

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish


    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: 	site4208.siteasp.net
        username: 	site4208
        password: ${{ secrets.SFTP_PASSWORD }}
        #local-dir: ./publish/
        server-dir: /wwwroot/
