name: Build and Deploy ISc Solution


on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore
    
      - name: Build the project
        run: dotnet build --configuration Release


      - name: publish my code 
        run: dotnet publish --configuration Release --output ./publish

      - name: List files before deployment
        run: |
          echo "Listing files in the publish directory:"
          ls -R ./publish

      - name: List files before deployment
        run: |
            echo "*****check the structure of the dir:*****"
            tree ./publish

      # - name: Deploy to FTP
      #   uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      #   with:
      #     server: site4208.siteasp.net
      #     username: site4208
      #     password: ${{ secrets.SFTP_PASSWORD }}
      #     local-dir: ./publish/
      #     server-dir: /wwwroot/
