name: Build and Deploy All Files

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release

      - name: Deploy all files to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: site4208.siteasp.net
          username: site4208
          password: ${{ secrets.SFTP_PASSWORD }}
          local-dir: ./
          server-dir: /wwwroot/
